export const categories = [
    "general",
    "business",
    "entertainment",
    "health",
    "science",
    "sports",
    "technology",
  ];


  export 
  const data={
    pagination: { limit:25, 
      offset:0,
       count: 25, total: 7945 },
  
    data: [
      {
        author: 'Irena Hwang, ProPublica',
        title: 'A Pandemic-Fueled Drop in FDA Inspections of Foreign Drug Plants',
        description: 'For decades, a federal watchdog agency has warned that the number of FDA inspections at overseas drug plants was worryingly low — and then Covid-19 slowed inspections to a trickle. But three years after the pandemic started, the FDA has been slow to return to pre-pandemic inspection rates.',
        url: 'https://undark.org/2023/04/26/a-pandemic-fueled-drop-in-fda-inspections-of-foreign-drug-plants/',
        source: 'Truth Beauty Science. - Undark',
        image: 'https://undark.org/wp-content/uploads/2023/04/fda-building.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T07:44:56+00:00'
      },
      {
        author: 'Regina Hartleb',
        title: 'Buchtipp „Rebellen der Erde“: Wie wir die Erde retten und uns selbst',
        description: 'Benedikt Bösel war zehn Jahre Investmentbanker. Dann übernahm er das riesige Landgut seiner Eltern in Brandenburg. Und machte daraus eine Oase, in der er zeigt, wie Landwirtschaft im Einklang mit der Natur gelingen kann. Die Abenteuerreise eines Pioniers.',
        url: 'https://rp-online.de/kultur/buch/buch-von-benedikt-boesel-rebellen-vom-feld_aid-89071153',
        source: 'RP Onlione Wissenschaft',
        image: 'https://rp-online.de/imgs/32/1/6/4/2/6/6/4/5/3/tok_5682ae42eb38ea1b51b8a691a072159b/w950_h950_x2134_y3474_Benedikt_Boesel__c__Emanuel_Finckenstein-2295c9ca88e42761.jpg',
        category: 'science',
        language: 'de',
        country: 'de',
        published_at: '2023-04-26T07:14:00+00:00'
      },
      {
        author: null,
        title: 'Woodpecker guides post-fire forest management',
        description: "What's good for the Black-backed Woodpecker is good for restoration of burned California forests. The birds' unique relationship with fire underpins the latest research into improved post-fire management. A study published in Ecological Applications describes a new tool that factors how fires burn into forest management decisions and turns science into action for wildlife conservation.",
        url: 'https://phys.org/news/2023-04-woodpecker-post-fire-forest.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/woodpecker-guides-post-1.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T05:38:22+00:00'
      },
      {
        author: null,
        title: 'Global research reveals countries where record-breaking heat waves are likely to cause most harm',
        description: 'A new study has highlighted underprepared regions across the world most at risk of the devastating effects of scorching temperatures.',
        url: 'https://phys.org/news/2023-04-global-reveals-countries-record-breaking.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/global-research-reveal-1.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T05:38:12+00:00'
      },
      {
        author: null,
        title: 'Self-driving lab accelerates the discovery process for materials with multiple applications',
        description: 'Researchers have a new scientific tool called Polybot, combining the power of artificial intelligence with robotics. Potential applications include speeding up the discovery of wearable biomedical devices, materials for better batteries and more.',
        url: 'https://phys.org/news/2023-04-self-driving-lab-discovery-materials-multiple.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/argonnes-self-driving.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T05:38:07+00:00'
      },
      {
        author: null,
        title: 'Researchers find lifesaving impact of early warning systems in Ukraine',
        description: "As many as 45% of casualties were prevented in the first few months of the war in Ukraine through heightened public responsiveness and the Ukrainian government's communications strategy, according to a new study by researchers from the University of Michigan, the University of Chicago and Ipsos.",
        url: 'https://phys.org/news/2023-04-lifesaving-impact-early-ukraine.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/ukraine-1.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T05:37:40+00:00'
      },
      {
        author: 'Written by Jennie Agg, read by Emma Powell and originally produced by Esther Opoku-Gyeni, with additions and scoring by Jack Claramunt. The executive producer was Ellie Bury',
        title: 'From the archive: My four miscarriages: why is losing a pregnancy so shrouded in mystery? – podcast',
        description: 'We are exploring the Guardian Long Read archives to bring you some classic pieces from years past, with new introductions from the authors.This week, from 2020: After losing four pregnancies, Jennie Agg set out to unravel the science of miscarriage. Then, a few months in, she found out she was pregnant again – just as the coronavirus pandemic hit Continue reading...',
        url: 'https://www.theguardian.com/news/audio/2023/apr/26/from-the-archive-my-four-miscarriages-why-is-losing-a-pregnancy-so-shrouded-in-mystery-podcast',
        source: 'The Guardian',
        image: 'https://i.guim.co.uk/img/media/8ed8e14b2d8845b6e907dda458c4fcb0749e490f/0_0_4871_2922/master/4871.jpg?width=140&quality=85&auto=format&fit=max&s=0b52e003e7b9f330da69f257b511d244',
        category: 'science',
        language: 'en',
        country: 'gb',
        published_at: '2023-04-26T04:00:51+00:00'
      },
      {
        author: null,
        title: 'Astronomers solve the 60-year mystery of quasars, the most powerful objects in the universe',
        description: 'Scientists have unlocked one of the biggest mysteries of quasars—the brightest, most powerful objects in the universe—by discovering that they are ignited by galaxies colliding.',
        url: 'https://phys.org/news/2023-04-astronomers-year-mystery-quasars-powerful.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/astronomers-solve-the.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T00:01:04+00:00'
      },
      {
        author: null,
        title: "Researcher's new book reveals spirituality is a powerful force in women's prisons",
        description: "A subject treated as an afterthought in many studies of imprisonment—religion—and an incarcerated group often regarded as peripheral—women—are the core of a University of Maryland researcher's groundbreaking new book on the deep spirituality that, perhaps not surprisingly, exists behind bars.",
        url: 'https://phys.org/news/2023-04-reveals-spirituality-powerful-women-prisons.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/researchers-new-book-r.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T21:16:04+00:00'
      },
      {
        author: null,
        title: 'Hispanics with disabilities making historic rebound in job market post-COVID-19 shutdown',
        description: 'New data shows that Hispanics with disabilities in the United States rebounded to historic levels in the labor force following the first 12-month period of the COVID-19 pandemic. While the disparity between their non-Hispanic white counterparts remains, their recovery has narrowed this gap and surpassed that of their Black/African American counterparts, according to experts speaking during a recent nTIDE Deeper Dive Lunch & Learn Webinar.',
        url: 'https://phys.org/news/2023-04-hispanics-disabilities-historic-rebound-job.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/ntide-april-2023-deepe.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T21:14:03+00:00'
      },
      {
        author: null,
        title: 'Patient capital is in short supply, research finds',
        description: 'Investors demand returns—and many want them to materialize overnight. But not every investment opportunity has that kind of potential. Some take years to pay off, but yield big results when they do.',
        url: 'https://phys.org/news/2023-04-patient-capital-short.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2019/stocks.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T21:03:03+00:00'
      },
      {
        author: null,
        title: 'COVID market disruptions were tougher on small firms spread up and down supply chain, study finds',
        description: 'While diversification may be universally lauded for reducing risk in your retirement savings and improving your diet, not all diversification is equally advantageous for small businesses. According to a new study from the University of Wisconsin–Madison, small businesses need to diversify in the right direction to avoid risk and remain resilient during tough times.',
        url: 'https://phys.org/news/2023-04-covid-disruptions-tougher-small-firms.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/food-supply-chain.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T20:59:03+00:00'
      },
      {
        author: null,
        title: 'NASA retires mineral mapping instrument on Mars Reconnaissance Orbiter',
        description: "NASA switched off one of its oldest instruments studying Mars on April 3, a step that's been planned since last year. Riding aboard NASA's Mars Reconnaissance Orbiter, CRISM, or the Compact Reconnaissance Imaging Spectrometer for Mars, revealed minerals such as clays, hematite (otherwise known as iron oxide), and sulfateh across the Red Planets surface for 17 years.",
        url: 'https://phys.org/news/2023-04-nasa-mineral-instrument-mars-reconnaissance.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/nasa-retires-mineral-m.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T20:58:02+00:00'
      },
      {
        author: null,
        title: 'State of the Climate report: Temperature, sea level continue to rise in New Jersey',
        description: "New Jersey's summer of 2022, with the warmest August on record and the lowest rainfall levels seen in more than 50 years, offers a glimpse into how climate change may affect future summers in the Garden State, according to a new report being released by researchers from Rutgers and the Office of the New Jersey State Climatologist.",
        url: 'https://phys.org/news/2023-04-state-climate-temperature-sea-jersey.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2022/climate-change-17.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T20:57:03+00:00'
      },
      {
        author: null,
        title: 'Wealthy white homeowners more likely to see financial benefits from land conservation, study shows',
        description: 'Land conservation projects do more than preserve open space and natural ecosystems. They can also boost property values for homeowners living nearby. But a new study finds that those financial benefits are unequally distributed among demographic groups in the U.S.',
        url: 'https://phys.org/news/2023-04-wealthy-white-homeowners-financial-benefits.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2018/greenneighbo.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T20:49:04+00:00'
      },
      {
        author: null,
        title: 'A pioneering artificial intelligence method to fight urban air pollution',
        description: "99% of the world's population breathes air that exceeds the limits recommended by the World Health Organization (WHO). This scenario is exacerbated in urban areas where more than 50% of the world's population is concentrated.",
        url: 'https://phys.org/news/2023-04-artificial-intelligence-method-urban-air.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/a-pioneering-artificia.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T19:59:43+00:00'
      },
      {
        author: null,
        title: 'New motion blur restoration approach for improved weed detection in crop fields',
        description: 'Effective weed control is crucial in agriculture to ensure high crop productivity. It entails the careful separation of weeds from crops before herbicides are sprayed in the fields. In simple terms, the goal of weed control is to remove the weeds while ensuring that the crop are not harmed. Traditional weed control methods have several drawbacks, such as crop contamination, herbicide waste, and poor accuracy. Therefore, it is essential to develop methods that can precisely locate and identify the boundary between a crop and weed and implement better weed control.',
        url: 'https://phys.org/news/2023-04-motion-blur-approach-weed-crop.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2023/new-motion-blur-restor.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T19:57:24+00:00'
      },
      {
        author: null,
        title: 'Norway irked over Swedish rocket crash on its turf',
        description: 'The Norwegian foreign ministry expressed irritation Tuesday with Sweden for not immediately informing it of a research rocket that crashed in Norway, in a rare spat between the two neighbours.',
        url: 'https://phys.org/news/2023-04-norway-irked-swedish-rocket-turf.html',
        source: 'Phys.org - News And Articles On Science And Technology',
        image: 'https://scx1.b-cdn.net/csz/news/tmb/2020/3-space.jpg',
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T19:48:45+00:00'
      },
      {
        author: '',
        title: 'M926 Chloride Analyser and Active Salt Software Package from Sherwood Scientific',
        description: 'For many years Sherwood Scientific&rsquo;s Model 926 Chloride Analyser has been used for salt measurement by food ingredient suppliers and food manufacturers throughout the world.&nbsp; The M926 offers many benefits over other methods for Chloride determination.&nbsp;Simplicity, speed, and accuracy, are all important and well established with no requirement to make reagents....',
        url: 'https://www.labbulletin.com/articles/M926-Chloride-Analyser-and-Active-Salt-Software-Package',
        source: 'Lab Bulletin',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T07:50:14+00:00'
      },
      {
        author: null,
        title: 'Neue Datenbank zu semiaquatischen Insekten',
        description: 'Der Name täuscht: Eintagsfliegen halten sich monatelang als Larven in Gewässern auf, ehe sie als erwachsenes Tier nach kurzer Zeit sterben. Auch Steinfliegen, Köcherfliegen und Libellen verbringen den Großteil ihres Lebens als Larve im Wasser. Die semiaquatischen Insekten können ökologische Probleme früh anzeigen. Eine neue Datenbank soll dabei helfen.',
        url: 'https://science.orf.at/stories/3218968/',
        source: 'ORF.at Science',
        image: null,
        category: 'science',
        language: 'de',
        country: 'at',
        published_at: '2023-04-26T07:14:38+00:00'
      },
      {
        author: '',
        title: 'Diving deep for a sustainable alternative to eradicate single-use plastics',
        description: 'Sustainable material innovation company, Kelpi (Bristol, UK), is using Asynt&rsquo;s DrySyn oil-free heating blocks and CondenSyn waterless air condensers in their fight against marine plastic pollution and single-use plastics manufactured from fossil fuels. Dr Stefanie Federle, Chief Scientific Officer, explained that &ldquo;Kelpi is here to end the madness of using fossil fuels to create largely unrecycled, single-use packaging that takes hundreds of years to degrade, poisoning our oceans and polluting our landscape....',
        url: 'https://www.labbulletin.com/articles/diving-deep-sustainable-alternative-eradicate-singleuse',
        source: 'Lab Bulletin',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T07:00:19+00:00'
      },
      {
        author: '',
        title: 'Life science products for a greener lab.',
        description: 'A recent blog post from AMSBIO introduces a selection of the &lsquo;green products&rsquo; it offers to life science researchers looking to maintain rigorous scientific standards in their lab whilst also trying to minimize environmental impact. Laboratories are known to consume a significant amount of energy and produce a considerable amount of waste. However, with the increasing awareness of the importance of sustainability, many life sciences labs are taking steps towards prioritizing sustainable products and practices...',
        url: 'https://www.labbulletin.com/articles/life-science-products-greener-lab',
        source: 'Lab Bulletin',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T06:55:18+00:00'
      },
      {
        author: '',
        title: 'INTEGRA Biosciences’ new eBook: all you need to know about ELISAs',
        description: 'INTEGRA Biosciences is pleased to announce the release of a new eBook providing a complete guide to ELISAs. This resource is relevant for users at all levels of expertise and experience, regardless of their specific application, and is completely free to download.&nbsp;The eBook contains plenty of in-depth educational articles, relevant app notes and user testimonials that will help readers understand all the details behind how ELISAs work...',
        url: 'https://www.labbulletin.com/articles/integra-biosciences-new-ebook-all-you-need-know-about',
        source: 'Lab Bulletin',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T06:10:14+00:00'
      },
      {
        author: 'Brian Wang',
        title: 'Pictures of The Most Powerful Launch Vehicle Ever',
        description: 'Here are more pictures showing the power of the SpaceX Starship. The world’s most powerful launch vehicle ever developed pic.twitter.com/oYnZON31mm &#8212; SpaceX (@SpaceX) April 25, 2023 pic.twitter.com/bIRxZafD6A &#8212; RTF (@RTFnfa) April 25, 2023 Starship liftoff in slow motion pic.twitter.com/KqHjqwP88Z &#8212; Elon Musk (@elonmusk) April 22, 2023',
        url: 'https://www.nextbigfuture.com/2023/04/pictures-of-the-most-powerful-launch-vehicle-ever.html',
        source: 'Next Big Future',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-26T03:21:00+00:00'
      },
      {
        author: 'Kenneth Chang',
        title: 'Japanese Company’s Spacecraft Is Lost During Moon Landing Attempt',
        description: 'The Japanese company aimed to be the first to change the paradigm for transporting things to the moon, but that will have to wait for a future mission.',
        url: 'https://www.nytimes.com/2023/04/25/science/ispace-has-lost-contact-with-its-moon-lander.html',
        source: 'The New York Times',
        image: null,
        category: 'science',
        language: 'en',
        country: 'us',
        published_at: '2023-04-25T19:51:34+00:00'
      }
    ]
  }
  